import type { Lesson } from "../types/lesson";
export const AUDIO_DEFAULTS={voice:"af_sarah",speed:1,language:"en-us",modelVersion:"kokoro-v1.0",normalizationVersion:1,format:"wav"} as const;
export interface AudioConfig {voice:string;speed:number;language:string;modelVersion:string;normalizationVersion:number;format:"wav"}
export interface AudioPreloadItem {lessonId:string;itemId:string;text:string;sourceType:"shadowing"|"example"|"sentence-mining"|"vocabulary";priority:number;config:AudioConfig}
export function normalizeAudioText(text:string):string{return text.replace(/\s+/g," ").trim();}
export function rateToKokoroSpeed(rate:number):number{return Math.min(Math.max(rate/0.86,0.65),1.35);}
export function canonicalAudioInput(text:string,config:AudioConfig):string{return `text=${normalizeAudioText(text)}\nvoice=${config.voice}\nspeed=${config.speed}\nlanguage=${config.language}\nmodel=${config.modelVersion}\nnormalization=${config.normalizationVersion}\nformat=${config.format}`;}
export function selectLessonAudioPreloadItems(lesson:Lesson,limit=15):AudioPreloadItem[]{const raw:Array<Omit<AudioPreloadItem,"lessonId"|"config">>=[...lesson.deepPractice.shadowingPractice.lines.slice(0,5).map(x=>({itemId:x.id,text:x.line,sourceType:"shadowing" as const,priority:2})),...lesson.exampleSentences.slice(0,5).map(x=>({itemId:x.id,text:x.sentence,sourceType:"example" as const,priority:3})),...lesson.deepPractice.sentenceMining.slice(0,3).map(x=>({itemId:x.id,text:x.sentence,sourceType:"sentence-mining" as const,priority:4})),...lesson.vocabulary.filter(x=>x.context).slice(0,5).map(x=>({itemId:x.id,text:x.context!,sourceType:"vocabulary" as const,priority:5}))];const seen=new Set<string>();return raw.filter(x=>{const n=normalizeAudioText(x.text);if(!n||n.length>650||seen.has(n))return false;seen.add(n);return true;}).slice(0,limit).map(x=>({...x,lessonId:lesson.id,config:{...AUDIO_DEFAULTS,speed:rateToKokoroSpeed(x.sourceType==="shadowing"?0.78:0.82)}}));}
export interface QueueJob {key:string;request:()=>Promise<string>;priority:number;lessonId:string;status:"queued"|"generating"|"ready"|"failed"|"cancelled";queuedAt:number}
export class AudioQueue {private jobs=new Map<string,QueueJob>();private waiters=new Map<string,Promise<string>>();private active=0;constructor(private concurrency=1){}enqueue(job:Omit<QueueJob,"status"|"queuedAt">):Promise<string>{const old=this.jobs.get(job.key);if(old&&job.priority<old.priority)old.priority=job.priority;const waiting=this.waiters.get(job.key);if(waiting)return waiting;const full:{job:QueueJob;resolve:(v:string)=>void;reject:(e:unknown)=>void}={job:{...job,status:"queued",queuedAt:Date.now()},resolve:()=>{},reject:()=>{}};const promise=new Promise<string>((resolve,reject)=>{full.resolve=resolve;full.reject=reject});this.jobs.set(job.key,full.job);this.waiters.set(job.key,promise);(full.job as QueueJob&{resolve?:(v:string)=>void;reject?:(e:unknown)=>void}).resolve=full.resolve;(full.job as QueueJob&{resolve?:(v:string)=>void;reject?:(e:unknown)=>void}).reject=full.reject;this.pump();return promise;}cancelLesson(id:string){for(const job of this.jobs.values())if(job.lessonId===id&&job.status==="queued"&&job.priority>1){job.status="cancelled";(job as QueueJob&{reject?:(e:unknown)=>void}).reject?.(new Error("cancelled"));this.finish(job.key);}}private finish(k:string){this.jobs.delete(k);this.waiters.delete(k);}private pump(){while(this.active<this.concurrency){const next=[...this.jobs.values()].filter(x=>x.status==="queued").sort((a,b)=>a.priority-b.priority||a.queuedAt-b.queuedAt)[0];if(!next)return;next.status="generating";this.active++;next.request().then(v=>{next.status="ready";(next as QueueJob&{resolve?:(v:string)=>void}).resolve?.(v)}).catch(e=>{next.status="failed";(next as QueueJob&{reject?:(e:unknown)=>void}).reject?.(e)}).finally(()=>{this.active--;this.finish(next.key);this.pump()});}}}
