import { createHash } from "node:crypto";
import { stripJsonFences } from "./lesson-schema";
export type SentenceCheckVerdict="clear"|"needs_small_fix"|"needs_rewrite"|"unclear";
export interface SentenceCheckResult{understandable:boolean;verdict:SentenceCheckVerdict;correctedSentence:string;naturalAlternative:string|null;explanationVi:string}
const verdicts=new Set<SentenceCheckVerdict>(["clear","needs_small_fix","needs_rewrite","unclear"]);
export function normalizeSentenceInput(value:string){return value.trim().replace(/\s+/g," ");}
export function sentenceInputHash(value:string){return createHash("sha256").update(normalizeSentenceInput(value),"utf8").digest("hex");}
export function validateSentenceInput(value:string,pattern:string,original:string):string|null{const text=normalizeSentenceInput(value);if(!text)return "Write your sentence before checking it.";if(text.length>500)return "Your sentence must be 500 characters or fewer.";if((text.match(/[A-Za-z]+(?:'[A-Za-z]+)?/g)??[]).length<3)return "Write at least three words so the sentence can be checked.";if(/_{3,}/.test(text))return "Fill in the blank before checking your sentence.";if(normalizeSentenceInput(pattern)===text)return "Fill in the useful pattern with your own details.";if(!/[A-Za-z]/.test(text)||((text.match(/[^\p{L}\p{N}\s.,!?;:'’"()-]/gu)??[]).length>Math.max(3,text.length/4)))return "Use a natural-language sentence with fewer symbols.";if(text===normalizeSentenceInput(original))return null;return null;}
export function parseSentenceCheck(raw:string):SentenceCheckResult{const value=JSON.parse(stripJsonFences(raw)) as Record<string,unknown>,keys=Object.keys(value).sort().join(",");if(keys!=="correctedSentence,explanationVi,naturalAlternative,understandable,verdict"||typeof value.understandable!=="boolean"||typeof value.verdict!=="string"||!verdicts.has(value.verdict as SentenceCheckVerdict)||typeof value.correctedSentence!=="string"||!value.correctedSentence.trim()||value.correctedSentence.length>500||(value.naturalAlternative!==null&&(typeof value.naturalAlternative!=="string"||!value.naturalAlternative.trim()||value.naturalAlternative.length>500))||typeof value.explanationVi!=="string"||!value.explanationVi.trim()||value.explanationVi.length>500||/```|\*\*/.test(`${value.correctedSentence}${value.naturalAlternative??""}${value.explanationVi}`))throw new Error("Invalid sentence-check result.");return {understandable:value.understandable,verdict:value.verdict as SentenceCheckVerdict,correctedSentence:value.correctedSentence.trim(),naturalAlternative:typeof value.naturalAlternative==="string"?value.naturalAlternative.trim():null,explanationVi:value.explanationVi.trim()};}
export function isSentenceFeedbackStale(draft:string,inputHash:string){return sentenceInputHash(draft)!==inputHash;}
