import { NextResponse } from "next/server";
import { buildSpeakingSession } from "@/lib/speaking-practice";
import { generateSentenceCheck } from "@/lib/openai";
import { normalizeSentenceInput, sentenceInputHash, validateSentenceInput } from "@/lib/sentence-check";
import { assertBackupCapacity } from "@/server/backup/backup";
import { getStorageContext } from "@/server/storage";
import { isRecord, readJsonBody, storageErrorResponse } from "@/server/storage/api";
import { StorageError } from "@/server/storage/errors";
import type { Lesson } from "@/types/lesson";
export const runtime="nodejs";
export const dynamic="force-dynamic";
const inFlight=new Set<string>();
export async function POST(request:Request){try{const body=await readJsonBody(request,4_000);if(!isRecord(body)||typeof body.lessonId!=="string"||typeof body.sessionId!=="string"||typeof body.sentence!=="string")throw new StorageError("VALIDATION_ERROR","Sentence-check request is invalid.");const db=getStorageContext().database,row=db.prepare("SELECT * FROM speaking_sessions WHERE id=? AND lesson_id=? AND status='active'").get(body.sessionId,body.lessonId) as Record<string,unknown>|undefined;if(!row)throw new StorageError("NOT_FOUND","Speaking session was not found.");const lessonRow=db.prepare("SELECT lesson_json FROM lessons WHERE id=? AND deleted_at IS NULL").get(body.lessonId) as {lesson_json:string}|undefined;if(!lessonRow)throw new StorageError("NOT_FOUND","Lesson was not found.");const lesson=JSON.parse(lessonRow.lesson_json) as Lesson,ids=JSON.parse(String(row.item_ids_json)) as string[],itemId=ids[Number(row.current_item_index)],task=buildSpeakingSession(lesson).find(x=>x.id===itemId);if(!task)throw new StorageError("VALIDATION_ERROR","Speaking item does not belong to this session.");const error=validateSentenceInput(body.sentence,task.personalization,task.text);if(error)throw new StorageError("VALIDATION_ERROR",error);const key=`${body.sessionId}:${itemId}`;if(inFlight.has(key))throw new StorageError("CONFLICT","This sentence is already being checked.");inFlight.add(key);try{const sentence=normalizeSentenceInput(body.sentence),result=await generateSentenceCheck({original:task.text,question:task.personalizationQuestion,pattern:task.personalization,targetPhrase:task.targetPhrase,sentence}),inputHash=sentenceInputHash(sentence),checkedAt=new Date().toISOString(),checks=JSON.parse(String(row.checks_json||"{}")) as Record<string,unknown>;checks[itemId]={...result,inputHash,checkedAt,inputText:sentence};db.exec("BEGIN IMMEDIATE");try{db.prepare("UPDATE speaking_sessions SET checks_json=?,updated_at=? WHERE id=?").run(JSON.stringify(checks),checkedAt,body.sessionId);assertBackupCapacity(db);db.exec("COMMIT");}catch(error){db.exec("ROLLBACK");throw error;}return NextResponse.json({result:{...result,inputHash,checkedAt,inputText:sentence}});}finally{inFlight.delete(key);}}
catch(error){if(error instanceof StorageError)return storageErrorResponse(error);if(error instanceof Error&&error.message.includes("GEMINI_API_KEY"))return NextResponse.json({error:"Sentence checking requires an AI provider. Your draft is still saved, and you can continue speaking practice without checking it.",code:"PROVIDER_REQUIRED"},{status:503});if(error instanceof Error&&(error.name==="TimeoutError"||error.name==="AbortError"))return NextResponse.json({error:"Sentence checking timed out. Your draft is still saved.",code:"PROVIDER_TIMEOUT"},{status:504});return NextResponse.json({error:"The AI sentence checker is temporarily unavailable. Your draft is still saved, so you can try again or continue speaking practice.",code:"PROVIDER_UNAVAILABLE"},{status:502});}}

