import { spawn } from "node:child_process";
import { mkdtemp, rm, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
const root=await mkdtemp(join(tmpdir(),"pel-speaking-e2e-")),port="3226",base=`http://127.0.0.1:${port}`,serverPath=resolve(".next","standalone","server.js");
const server=spawn(process.execPath,[serverPath],{cwd:process.cwd(),env:{...process.env,HOSTNAME:"127.0.0.1",PORT:port,PERSONAL_ENGLISH_LAB_DATA_DIR:join(root,"data"),SENTENCE_CHECK_MOCK:"1"},stdio:["ignore","ignore","pipe"]});let stderr="";server.stderr.on("data",x=>stderr+=x);
const id=()=>crypto.randomUUID(),now=new Date().toISOString(),item=(extra)=>({id:id(),...extra}),lessonId=id();
const lesson={id:lessonId,schemaVersion:1,createdAt:now,updatedAt:now,title:"Speaking E2E",summary:"Temporary speaking smoke lesson.",vocabulary:Array.from({length:20},(_,i)=>item({word:`word ${i}`,phonetic:"/wɜːd/",definition:"definition",vietnamese:"từ",...(i===0?{context:"I use this word in a real conversation."}:{})})),idiomsAndSlang:[item({phrase:"keep going",meaning:"continue",vietnamese:"tiếp tục"})],exampleSentences:Array.from({length:5},(_,i)=>item({sentence:i===0?"I need to stop focusing on the end goal and enjoy the process.":`I keep practicing English for ${i+10} minutes every day.`,keyPhrase:i===0?"enjoy the process":"keep practicing",vietnamese:"Câu"})),quiz:Array.from({length:5},()=>item({question:"Question?",options:["A","B","C","D"],correctAnswer:0,explanation:"Explanation"})),deepPractice:{shadowingPractice:{steps:["1","2","3"],lines:[item({line:"I_keep / moving forward.",focus:"keep moving",vietnamese:"dòng"}),item({line:"Small habits make English feel natural.",focus:"small habits",vietnamese:"dòng"}),item({line:"I practice even when motivation is low.",focus:"keep practicing",vietnamese:"dòng"})]},sentenceMining:Array.from({length:3},(_,i)=>item({sentence:`Consistency helps me improve step ${i+1}.`,pattern:"helps me",whyUseful:"useful",remixPrompt:"remix"})),reviewPlan:[1,2,4,7].map(day=>({day:`Day ${day}`,task:"review"})),ankiCards:Array.from({length:5},()=>item({front:"Front",back:"Back"}))}};
const call=async(action,extra={})=>{const r=await fetch(`${base}/api/speaking`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,lessonId,...extra})});const j=await r.json();if(!r.ok)throw new Error(`${action} failed ${r.status}: ${JSON.stringify(j)}`);if(action==="start"){const task=j.tasks?.find(x=>x.text==="I need to stop focusing on the end goal and enjoy the process.");if(!task||task.recallMask.includes("enjoy the process")||task.keywords.join(" · ")!=="stop focusing · end goal · enjoy the process"||task.personalization!=="I need to stop focusing on ______ and start ______."||!task.steps.includes("free_speak"))throw new Error("guided ladder quality checks failed");}return j;};
try{let health;for(let i=0;i<30;i++){try{const r=await fetch(`${base}/api/storage/health`);if(r.ok){health=await r.json();break;}}catch{}await new Promise(r=>setTimeout(r,300));}if(!health)throw new Error(`server failed ${stderr}`);if(health.schemaVersion!==11)throw new Error("schema is not v11");
 const create=await fetch(`${base}/api/storage/lessons`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lesson})});if(create.status!==201)throw new Error(`lesson create ${create.status}: ${await create.text()}`);
 const missingLesson=await fetch(`${base}/api/speaking`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"start",lessonId:id()})});if(missingLesson.status!==404)throw new Error("missing lesson was not rejected");
 const first=await call("start"),again=await call("start");if(!first.tasks.length||first.session.id!==again.session.id||first.session.currentStep!=="read")throw new Error("active session coalescing failed");let state=first;state=await call("advance",{sessionId:state.session.id,step:"recall"});state=await call("show_answer",{sessionId:state.session.id});state=await call("advance",{sessionId:state.session.id,step:"keywords"});state=await call("advance",{sessionId:state.session.id,step:"personalize"});state=await call("save_draft",{sessionId:state.session.id,draft:"I need honest myself about gaming."});const checked=await fetch(`${base}/api/speaking/check-sentence`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lessonId,sessionId:state.session.id,sentence:"I need honest myself about gaming."})});if(!checked.ok)throw new Error(`sentence check failed ${checked.status}: ${await checked.text()}`);const checkedBody=await checked.json();if(!checkedBody.result.naturalAlternative)throw new Error("sentence check feedback incomplete");const persisted=await call("status");if(!persisted.session.drafts[first.tasks[0].id]||!persisted.session.checks[first.tasks[0].id])throw new Error("draft/check persistence failed");state=await call("complete_item",{sessionId:state.session.id,rating:"hard",helped:true});
 const invalidStep=await fetch(`${base}/api/speaking`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"advance",lessonId,sessionId:state.session.id,step:"invalid"})});if(invalidStep.status!==400)throw new Error("invalid step was not rejected");const invalidSession=await fetch(`${base}/api/speaking`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"advance",lessonId,sessionId:id(),step:"recall"})});if(invalidSession.status!==404)throw new Error("invalid session was not rejected");if(JSON.stringify(first).includes("originalTranscript"))throw new Error("API leaked transcript");
 const resumed=await call("status");if(resumed.session.currentItemIndex!==1||resumed.session.currentStep!=="read")throw new Error("resume failed");state=resumed;while(state.session.status==="active"){const task=state.tasks[state.session.currentItemIndex];for(const step of task.steps.slice(1))state=await call("advance",{sessionId:state.session.id,step});state=await call("complete_item",{sessionId:state.session.id,rating:"easy",helped:false});}
 if(state.summary.practiced!==state.tasks.length||state.summary.neededAnswer!==1||state.summary.freeSpeak!==1)throw new Error("summary counters failed");const review=await call("review",{sessionId:state.session.id});if(review.tasks.length!==1||review.tasks[0].id!==first.tasks[0].id)throw new Error("difficult review failed");
 const exported=await fetch(`${base}/api/backup/export`);if(!exported.ok)throw new Error("backup export failed");const backup=await exported.json();if(backup.speakingProgress.length!==state.tasks.length||backup.speakingSessions.length<1)throw new Error("speaking backup incomplete");if(!backup.speakingSessions.some(s=>Object.keys(s.checks??{}).length))throw new Error("sentence feedback missing from backup");const audio=await fetch(`${base}/api/audio/cache`);if(![200,503].includes(audio.status))throw new Error(`audio route unexpected ${audio.status}`);const db=await stat(join(root,"data","personal-english-lab.sqlite3"));console.log(JSON.stringify({health,activeSessionCoalesced:true,resume:true,showAnswer:true,completed:true,summary:state.summary,difficultReview:true,backupSpeakingProgress:backup.speakingProgress.length,backupActiveSessions:backup.speakingSessions.length,audioRouteStatus:audio.status,databaseBytes:db.size},null,2));
}finally{server.kill();await Promise.race([new Promise(r=>server.once("exit",r)),new Promise(r=>setTimeout(r,2000))]);await rm(root,{recursive:true,force:true});}
